Ex_1_1_19
sinister389/AlgoLessons pull request #7
Opened 2017-05-25 18:24 UTC by sinister389

Фибоначчи

2017-05-28 06:50 UTC, be9 requested changes

2017-05-28 06:50 UTC, be9 commented on src/Ex_1_1_19/Fibonacci.java
> +        long[] F = new long[N + 1];
Массив лучше объявлять перед строчкой `F[0] = 0`. А то если передать сильно отрицательное `N`, то упадёт ещё до проверки `if (N < 0) { ... }`.

2017-05-28 06:50 UTC, be9 commented on src/Ex_1_1_19/Fibonacci.java
> +        return F[F.length - 1];
`return F[N]`, чего уж.

2017-06-20 19:10 UTC, sinister389 commented
Окей, измениния сейчас внесу.

2017-06-20 19:10 UTC, closed without merging